/**
 * dsh-service-control — shell completion generation for the `dsh` command.
 *
 * OpenClaw-style: generates static completion scripts for `dsh` (the
 * `--profile ctl` command surface), caches them under
 * `$DSH_HOME/completions/dsh.<ext>`, and can install the `source` line into
 * the user's shell profile. The script data comes from COMMAND_TREE in
 * lib/cli-startup.js so completion matches the parsed surface.
 */
import os from 'node:os'
import path from 'node:path'
import { COMMAND_TREE, COMMAND_DESCRIPTIONS } from './cli-startup.js'

export const COMPLETION_SHELLS = ['bash', 'zsh', 'fish']
export const COMPLETION_EXT = { bash: 'bash', zsh: 'zsh', fish: 'fish' }

/** Normalize a shell name; returns undefined for unknown values. */
export function normalizeShell(name) {
  const n = String(name || '').toLowerCase()
  if (n === 'bash' || n === 'zsh' || n === 'fish') return n
  return undefined
}

/** Detect the current shell from $SHELL. */
export function detectShell(env = process.env) {
  const base = (env.SHELL || '').split('/').pop()
  return normalizeShell(base) ?? 'zsh'
}

/** Resolve the completion cache directory ($DSH_HOME/completions). */
export function completionCacheDir(env = process.env) {
  const home = env.DSH_HOME || path.join(os.homedir(), '.dsh')
  return path.join(home, 'completions')
}

/** Cache file path for one shell. */
export function cacheFilePath(shell, env = process.env) {
  return path.join(completionCacheDir(env), `dsh.${COMPLETION_EXT[shell]}`)
}

/**
 * 各 shell「默认自动加载目录」中的目标文件路径——安装到这些位置后，
 * 对应 shell 启动时自动加载，不需要修改用户的 .zshrc / .bashrc 等。
 *   bash: $XDG_DATA_HOME/bash-completion/completions/dsh（bash-completion 包自动加载）
 *   zsh:  ~/.zsh/completions/_dsh（约定目录；需在 $fpath 中，oh-my-zsh 等框架已包含）
 *   fish: ~/.config/fish/completions/dsh.fish（fish 原生自动加载）
 */
export function installPath(shell, env = process.env) {
  const home = env.HOME || os.homedir()
  switch (shell) {
    case 'bash': {
      const xdg = env.XDG_DATA_HOME || path.join(home, '.local', 'share')
      return path.join(xdg, 'bash-completion', 'completions', 'dsh')
    }
    case 'zsh':
      return path.join(home, '.zsh', 'completions', '_dsh')
    case 'fish':
      return path.join(home, '.config', 'fish', 'completions', 'dsh.fish')
  }
}

/** Namespace → subcommand alias list, for embedding into scripts. */
function flatSubs(namespace) {
  const out = []
  for (const [sub, aliases] of Object.entries(COMMAND_TREE[namespace])) {
    out.push(sub, ...aliases)
  }
  return out.join(' ')
}

const NAMESPACES = 'self config svc systemd completions'

export function genBash() {
  const systemd = flatSubs('systemd')
  return `# bash completion for dsh — generated by dsh-service-control (do not edit)
# 安装方式：dsh --profile ctl completions --install
# 自动加载目录：~/.local/share/bash-completion/completions/dsh（bash-completion 包自动加载）

_dsh() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  local profiles
  profiles="$(ls \${DSH_HOME:-\$HOME/.dsh}/profiles 2>/dev/null | grep -v node_modules)"

  # 已出现 ctl profile（分离式/等号式/粘连短选项）时才补全命令树；
  # 必须覆盖 --profile=ctl 等号形式，否则该写法下命令树补全静默失效。
  local i have_ctl=0
  for ((i=1; i<COMP_CWORD; i++)); do
    case "\${COMP_WORDS[i]}" in
      --profile|-p)
        [[ "\${COMP_WORDS[i+1]}" == "ctl" ]] && have_ctl=1
        ;;
      --profile=ctl|-p=ctl|-pctl)
        have_ctl=1
        ;;
    esac
  done

  case "$prev" in
    --profile|-p)
      COMPREPLY=($(compgen -W "$profiles" -- "$cur"))
      return 0
      ;;
    --shell)
      COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
      return 0
      ;;
  esac

  if [[ "$have_ctl" == "1" ]]; then
    # 选项补全：当前词以 - 开头（或 --shell= 等号形式）时，
    # 按已输入的子命令补对应选项
    case "$cur" in
      --shell=*)
        COMPREPLY=($(compgen -W "bash zsh fish" -- "\${cur#--shell=}"))
        return 0
        ;;
      -*)
        case "$prev" in
          update)       COMPREPLY=($(compgen -W "--check" -- "$cur")); return 0 ;;
          logs|journal) COMPREPLY=($(compgen -W "-f --follow" -- "$cur")); return 0 ;;
          completions)  COMPREPLY=($(compgen -W "--shell --write-state --install" -- "$cur")); return 0 ;;
        esac
        ;;
    esac
    case "$prev" in
      self)      COMPREPLY=($(compgen -W "info i update" -- "$cur")); return 0 ;;
      config)      COMPREPLY=($(compgen -W "get set" -- "$cur")); return 0 ;;
      svc)         COMPREPLY=($(compgen -W "doctor d logs probe h" -- "$cur")); return 0 ;;
      systemd)     COMPREPLY=($(compgen -W "${systemd}" -- "$cur")); return 0 ;;
      completions) COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur")); return 0 ;;
    esac
    COMPREPLY=($(compgen -W "${NAMESPACES}" -- "$cur"))
  else
    COMPREPLY=($(compgen -W "--profile -p" -- "$cur"))
  fi
  return 0
}
complete -F _dsh dsh
`
}

export function genZsh() {
  // ⚠️ 生成的文件只能包含注释和单个 _dsh 函数定义。
  // zsh compinit 只会把「无顶层可执行代码」的 #compdef 文件注册为自动加载
  // 补全；任何顶层语句（如 compdef _dsh dsh 调用）都会让注册静默失效——
  // 按 TAB 无报错也无候选。注册完全依赖首行 #compdef 头（fpath 自动加载）。

  /**
   * 生成 zsh 数组元素行：'name:描述'（含别名条目）。
   * ⚠️ 候选必须用真正的 zsh 数组传给 _describe，禁止字符串字面量列表：
   * '(...) ' 形式在部分 zsh 下会按空格切词，描述里的空格/引号会裂出
   * "status\"" 之类的垃圾候选。
   */
  const describeEntries = (ns, pad) => {
    const rows = []
    for (const [sub, aliases] of Object.entries(COMMAND_TREE[ns])) {
      const desc = COMMAND_DESCRIPTIONS[`${ns}.${sub}`] ?? sub
      rows.push(`${pad}'${sub}:${desc}'`)
      for (const alias of aliases) rows.push(`${pad}'${alias}:${sub} 的别名'`)
    }
    return rows.join('\n')
  }
  const cmdEntries = [
    ...Object.keys(COMMAND_TREE).map((ns) => `        '${ns}:${COMMAND_DESCRIPTIONS[ns] ?? ns}'`),
    "        'completions:shell 补全'",
  ].join('\n')

  return `#compdef dsh
# zsh completion for dsh — generated by dsh-service-control (do not edit)

_dsh() {
  local curcontext="$curcontext" state line
  typeset -A opt_args

  local -a profiles
  profiles=(\${DSH_HOME:-\$HOME/.dsh}/profiles/*(/N:t))
  profiles=(\${profiles:#node_modules})

  _arguments -C \\
    '--profile=[profile under DSH_HOME]:profile:->profiles' \\
    '1:command:->cmds' \\
    '*::argument:->args'

  case $state in
    (profiles)
      _describe -t profiles 'profile' profiles
      ;;
    (cmds)
      # 是否已指定 ctl profile：支持分离式与等号式（--profile=ctl），
      # 只认分离形式会导致等号写法下命令树补全静默失效。
      local i have_ctl=0
      for ((i = 2; i <= $#words; i++)); do
        case \${words[i]} in
          (--profile|-p)
            (( i < $#words )) && [[ "\${words[i+1]}" == "ctl" ]] && have_ctl=1
            ;;
          (--profile=*|-p=*|-pctl)
            [[ "\${words[i]#*=}" == "ctl" ]] && have_ctl=1
            ;;
        esac
      done
      if (( have_ctl )); then
        # 候选用真 zsh 数组传入 _describe（数组名形式），
        # 避免字符串字面量被按空格切词裂出垃圾候选。
        local -a cmds
        cmds=(
${cmdEntries}
        )
        _describe -t command 'command' cmds
      else
        # 尚未指定 --profile ctl：补全 --profile 选项（compadd 安全处理 - 开头匹配）
        compadd -- --profile
      fi
      ;;
    (args)
      # subs：该命名空间的子命令候选；opts：已输入子命令支持的选项。
      # 当前词以 - 开头时优先补全选项（compadd），否则补全子命令。
      local -a subs opts
      case $line[1] in
        (self)
          subs=(
${describeEntries('self', '            ')}
          )
          case $line[2] in
            (update) opts=(--check) ;;
          esac
          ;;
        (config)
          subs=(
${describeEntries('config', '            ')}
          )
          ;;
        (svc)
          subs=(
${describeEntries('svc', '            ')}
          )
          case $line[2] in
            (logs) opts=(-f --follow) ;;
          esac
          ;;
        (systemd)
          subs=(
${describeEntries('systemd', '            ')}
          )
          case $line[2] in
            (journal) opts=(-f --follow) ;;
          esac
          ;;
        (completions)
          subs=(
            'bash:bash 补全脚本'
            'zsh:zsh 补全脚本'
            'fish:fish 补全脚本'
          )
          opts=(--shell --write-state --install)
          ;;
      esac
      # --shell 的值补全（空格形式 + 等号形式）
      if [[ $line[1] == completions && \${words[CURRENT-1]} == --shell ]]; then
        _describe -t shell 'shell' subs
      elif [[ $line[1] == completions && $PREFIX == --shell=* ]]; then
        compadd -p '--shell=' -- bash zsh fish
      elif (( $#opts )) && [[ $PREFIX == -* ]]; then
        compadd -- $opts
      else
        (( $#subs )) && _describe -t sub 'subcommand' subs
      fi
      ;;
  esac
}
`
}

export function genFish() {
  const systemd = flatSubs('systemd')
  return `# fish completion for dsh — generated by dsh-service-control (do not edit)

function __dsh_profiles
    if set -q DSH_HOME
        ls $DSH_HOME/profiles 2>/dev/null | grep -v node_modules
    else
        ls ~/.dsh/profiles 2>/dev/null | grep -v node_modules
    end
end

complete -c dsh -l profile -s p -d 'profile under DSH_HOME' -a '(__dsh_profiles)'

# 命令行是否已出现 ctl profile（分离式/等号式/粘连短选项都算）；
# __fish_seen_subcommand_from ctl 认不出 --profile=ctl 等号形式。
function __dsh_have_ctl
    set -l tokens (commandline -opc)
    while set -q tokens[1]
        switch $tokens[1]
            case '--profile' '-p'
                if set -q tokens[2]; and test "$tokens[2]" = ctl
                    return 0
                end
            case '--profile=ctl' '-p=ctl' '-pctl'
                return 0
        end
        set -e tokens[1]
    end
    return 1
end

# 仅当命令行已出现 ctl 时补全命令树
complete -c dsh -n '__dsh_have_ctl' -a '${NAMESPACES}'
complete -c dsh -n '__fish_seen_subcommand_from self' -a 'info i update'
complete -c dsh -n '__fish_seen_subcommand_from config' -a 'get set'
complete -c dsh -n '__fish_seen_subcommand_from svc' -a 'doctor d logs probe h'
complete -c dsh -n '__fish_seen_subcommand_from systemd' -a '${systemd}'
complete -c dsh -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish'

# 子命令选项补全
complete -c dsh -n '__fish_seen_subcommand_from update' -l check -d '只预检，不实际更新'
complete -c dsh -n '__fish_seen_subcommand_from logs' -s f -l follow -d '跟随输出'
complete -c dsh -n '__fish_seen_subcommand_from journal' -s f -l follow -d '跟随输出'
complete -c dsh -n '__fish_seen_subcommand_from completions' -l shell -r -d '指定 shell' -a 'bash zsh fish'
complete -c dsh -n '__fish_seen_subcommand_from completions' -l write-state -d '缓存全部 shell 脚本到 $DSH_HOME/completions'
complete -c dsh -n '__fish_seen_subcommand_from completions' -l install -d '写入 shell profile'
`
}

/** Generate the script text for one shell. */
export function generateCompletion(shell) {
  switch (shell) {
    case 'bash': return genBash()
    case 'zsh': return genZsh()
    case 'fish': return genFish()
    default: throw new Error(`unsupported shell: ${shell}`)
  }
}
